apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    cluster.x-k8s.io/provider: infrastructure-gcp
  name: capg-manager
  namespace: capg-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    cluster.x-k8s.io/provider: infrastructure-gcp
  name: capg-leader-election-role
  namespace: capg-system
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - configmaps/status
  verbs:
  - get
  - update
  - patch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    cluster.x-k8s.io/provider: infrastructure-gcp
  name: capg-manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
- apiGroups:
  - cluster.x-k8s.io
  resources:
  - clusters
  - clusters/status
  - machinepools
  - machinepools/status
  - machines
  - machines/status
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - infrastructure.cluster.x-k8s.io
  resources:
  - gcpclusters
  - gcpmachines
  - gcpmanagedclusters
  - gcpmanagedcontrolplanes
  - gcpmanagedmachinepools
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - infrastructure.cluster.x-k8s.io
  resources:
  - gcpclusters/status
  - gcpmachines/status
  - gcpmanagedclusters/status
  - gcpmanagedcontrolplanes/status
  - gcpmanagedmachinepools/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - infrastructure.cluster.x-k8s.io
  resources:
  - gcpmanagedclusters/finalizers
  - gcpmanagedcontrolplanes/finalizers
  - gcpmanagedmachinepools/finalizers
  verbs:
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    cluster.x-k8s.io/provider: infrastructure-gcp
  name: capg-leader-election-rolebinding
  namespace: capg-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: capg-leader-election-role
subjects:
- kind: ServiceAccount
  name: capg-manager
  namespace: capg-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    cluster.x-k8s.io/provider: infrastructure-gcp
  name: capg-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: capg-manager-role
subjects:
- kind: ServiceAccount
  name: capg-manager
  namespace: capg-system
---
apiVersion: v1
data:
  credentials.json: ${GCP_B64ENCODED_CREDENTIALS}
kind: Secret
metadata:
  labels:
    cluster.x-k8s.io/provider: infrastructure-gcp
  name: capg-manager-bootstrap-credentials
  namespace: capg-system
type: Opaque
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    cluster.x-k8s.io/provider: infrastructure-gcp
    control-plane: capg-controller-manager
  name: capg-controller-manager
  namespace: capg-system
spec:
  replicas: 1
  selector:
    matchLabels:
      cluster.x-k8s.io/provider: infrastructure-gcp
      control-plane: capg-controller-manager
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        cluster.x-k8s.io/provider: infrastructure-gcp
        control-plane: capg-controller-manager
    spec:
      containers:
      - args:
        - --leader-elect
        - --feature-gates=GKE=${EXP_CAPG_GKE:=false}
        - --diagnostics-address=${CAPG_DIAGNOSTICS_ADDRESS:=:8443}
        - --insecure-diagnostics=${CAPG_INSECURE_DIAGNOSTICS:=false}
        - --v=${CAPG_LOGLEVEL:=0}
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /home/.gcp/credentials.json
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: gcr.io/k8s-staging-cluster-api-gcp/cluster-api-gcp-controller:e2e
        imagePullPolicy: Always
        name: manager
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          runAsGroup: 65532
          runAsUser: 65532
        terminationMessagePolicy: FallbackToLogsOnError
        volumeMounts:
        - mountPath: /home/.gcp
          name: credentials
      terminationGracePeriodSeconds: 10
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
      - effect: NoSchedule
        key: node-role.kubernetes.io/control-plane
      volumes:
      - name: credentials
        secret:
          secretName: capg-manager-bootstrap-credentials
